name: Build and Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 12 * * *'
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:  |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io/zkayyali812/ocm-utils:latest && \
        docker build . -t quay.io/zkayyali812/ocm-utils:latest && \
        docker push quay.io/zkayyali812/ocm-utils:latest